version: "3.9"

services: 
  auth:
    hostname: gateway
    container_name: kanbango-gateway
    build: .
    ports:
      - 5535:5535
    logging:
      options:
        max-size: "1m"
        max-file: "3"
      